SELECT
    b.AUTHOR_ID      AS AUTHOR_ID,
    a.AUTHOR_NAME    AS AUTHOR_NAME,
    b.CATEGORY       AS CATEGORY,
    SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a     ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES s ON s.BOOK_ID   = b.BOOK_ID
WHERE s.SALES_DATE >= '2022-01-01'
    AND s.SALES_DATE <  '2022-02-01'
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;
