SELECT c3.ID
FROM ECOLI_DATA AS c3
WHERE c3.PARENT_ID IN (
  SELECT c2.ID
  FROM ECOLI_DATA AS c2
  WHERE c2.PARENT_ID IN (
    SELECT c1.ID
    FROM ECOLI_DATA AS c1
    WHERE c1.PARENT_ID IS NULL
  )
)
ORDER BY c3.ID ASC;
