SELECT
  A.CAR_ID AS CAR_ID,
  A.CAR_TYPE AS CAR_TYPE,
  FLOOR(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
  ON C.CAR_TYPE = A.CAR_TYPE
 AND C.DURATION_TYPE = '30일 이상'
WHERE A.CAR_TYPE IN ('세단', 'SUV')
  -- 11월(1~30일)과 한 번이라도 겹치는 대여 기록이 "없어야" 대여 가능
  AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = A.CAR_ID
      -- 겹침 조건(양끝 포함): START <= 11/30 AND END >= 11/01
      AND H.START_DATE <= '2022-11-30'
      AND H.END_DATE   >= '2022-11-01'
  )
  -- 30일 요금 범위
  AND FLOOR(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY
  FEE DESC,
  A.CAR_TYPE ASC,
  A.CAR_ID DESC;
