select C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) as FEE
from CAR_RENTAL_COMPANY_CAR as C
JOIN (
  SELECT CAR_TYPE, DISCOUNT_RATE
  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
  WHERE DURATION_TYPE = '30일 이상'
) AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    and not exists (
        select 1
        from CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        where
            C.CAR_ID = H.CAR_ID
            and START_DATE <= '2022-11-30'
            and END_DATE >= '2022-11-01'
    )
    and FLOOR(C.DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) BETWEEN 500000 and 1999999
ORDER BY FEE desc, C.CAR_TYPE asc, C.CAR_ID desc