-- 코드를 입력하세요
select R.FOOD_TYPE, R.REST_ID, R.REST_NAME, M.MF
FROM REST_INFO as R
JOIN(
    SELECT FOOD_TYPE as FT,
        MAX(FAVORITES) as MF
    FROM REST_INFO
    GROUP BY FOOD_TYPE) as M
    ON M.MF = R.FAVORITES
        and M.FT = R.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC