-- 코드를 입력하세요
SELECT P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE * T.TOTAL as TOTAL_SALES
FROM FOOD_PRODUCT as P
JOIN
    (
    SELECT PRODUCT_ID,
        SUM(AMOUNT) as TOTAL
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' and '2022-05-31'
    GROUP BY PRODUCT_ID) as T
ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY TOTAL_SALES desc, P.PRODUCT_ID asc