-- 코드를 입력하세요
SELECT M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as R
JOIN (
    SELECT MEMBER_NAME, MEMBER_ID
    FROM MEMBER_PROFILE
    WHERE MEMBER_ID = (SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) desc
        LIMIT 1)
    ) as M
ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE asc