SELECT YEAR(E.DIFFERENTIATION_DATE) as YEAR,
    MAX_DATA.M_SIZE - E.SIZE_OF_COLONY as YEAR_DEV,
    E.ID as ID
FROM ECOLI_DATA as E
JOIN (
    SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') as YEAR,
        MAX(SIZE_OF_COLONY) as M_SIZE
    FROM ECOLI_DATA
    GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')) as MAX_DATA
    ON DATE_FORMAT(E.DIFFERENTIATION_DATE, '%Y') = MAX_DATA.YEAR
ORDER BY YEAR(E.DIFFERENTIATION_DATE) asc, YEAR_DEV asc