SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN (
  SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
  FROM FISH_INFO
  GROUP BY FISH_TYPE
) AS M
  ON I.FISH_TYPE = M.FISH_TYPE
 AND I.LENGTH = M.MAX_LENGTH
JOIN FISH_NAME_INFO AS N
  ON N.FISH_TYPE = I.FISH_TYPE
ORDER BY I.ID;